# Generated by Django 3.1.3 on 2021-06-04 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloghome',
            old_name='tittle',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='bloghome',
            name='slug',
            field=models.SlugField(blank=True, max_length=1000, null=True),
        ),
    ]
